[project]
name = "demon-cry-base"
dynamic = ["version"]
description = "Base module for demon-cry OSINT plugins"
authors = [
    {name = "mooncore-inc"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
version = "0.0.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
